public class Main {
    public static void main(String[] args) {

        // 1. Declara una variable int para almacenar una edad

        // 2. Declara una variable double para almacenar una altura

        // 3. Declara una variable char para almacenar una inicial

        // 4. Declara una variable String para almacenar un nombre

        // 5. Declara una variable boolean para indicar si es estudiante

        // 6. Imprime el nombre

        // 7. Imprime la edad

        // 8. Imprime la altura

        // 9. Imprime la inicial

        // 10. Imprime el valor de estudiante

    }
}